#!/bin/bash

CONTAINER_NAME="talently"

# Build Docker Image
docker build \
    --tag ${CONTAINER_NAME}:latest \
    .

# Run Container
docker run \
	--detach \
	--interactive \
	--tty \
	--rm \
	--volume D:\\PROJECTS\\PHP\\php-backend-challenge:/project \
	--name $CONTAINER_NAME \
	$CONTAINER_NAME

docker exec $CONTAINER_NAME composer install